### ISSUE TITLE
Add Jest-aXe

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-scripts#14]
**Is your feature request related to a problem? Please describe.**
The problem is accessibility. We want all operational UIs to be as accessible as they can be. https://github.com/nickcolley/jest-axe will help with that.

**Describe the solution you'd like**
https://github.com/nickcolley/jest-axe

**Comment by fabien0102** [comment]
Just to add more tools to benchmark https://css-tricks.com/accessibility-testing-tools/

This one https://github.com/addyosmani/a11y, looks also nice 💯

**Comment by TejasQ** [comment]
Closing because this really should be a part of Operational instead.
