### ISSUE TITLE
Symlink is not working on windows (EPERM)

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-scripts#3]
**Describe the bug**
The installation doesn't work on windows

**To Reproduce**

1. Create an empty project
1. `git init && npm init -y`
1. `npm i -D @operational/scripts`
1. `EPERM: operation not permitted`

**Expected behavior**

**Screenshots**

On git-bash
![image](https://user-images.githubusercontent.com/1761469/44617010-87e19b80-a85b-11e8-9f55-b4fa8b0bb11d.png)

On power-shell
![image](https://user-images.githubusercontent.com/1761469/44617068-c7f54e00-a85c-11e8-967f-a56703e7bb96.png)

(=> `true is not recognized as an internal or external command operable program or batch file`)

**Desktop:**
 - OS: Microsoft Windows 10 Professionnel - 10.0.17744 N/A version 17744
 - bash version: GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)
 - operational/scripts version: 1.0.2

**Idea to resolve this issue**:
- https://www.npmjs.com/package/lnk

**Comment by TejasQ** [comment]
Good catch! Wanna make a PR?
